unit HELPCAD;

interface

const

  hcAbout                = 9;
  hcChangeDirBox         = 14;
  hcDOSShell             = 65287;
  hcEdit                 = 12;
  hcFileLoadBox          = 15;
  hcFiles                = 10;
  hcFileSaveBox          = 16;
  hcGraphID              = 3;
  hcHelp                 = 13;
  hcMainMenu             = 7;
  hcMenuBar              = 4;
  hcNoContext            = 0;
  hcPrint                = 11;
  hcSubMenu              = 6;
  hcSystem               = 8;
  hcTextID               = 2;
  hcUseHelp              = 1;
  hcWindow               = 5;

implementation

end.
